name: Sync Code base
on:
  push:
    branches:
      - master

jobs:
  update-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        host: ${{ secrets.VM_IP_ADDRESS }}
        port: 22
        user: ${{ secrets.VM_USERNAME }}
        pass: ${{ secrets.VM_PASSWORD }}
      run: |
        pwd
        ls -l
        cd /home/devops/Assessment/nodejs-webapp && git pull

    # - name: Create SSH directory
    #   run: |
    #     mkdir -p ~/.ssh

    # - name: Set Up SSH
    #   run: |
    #     echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    #     chmod 600 ~/.ssh/id_rsa
    # - name: Pull Code
    #   run: |
    #     pwd
    #     ls -l
    #     cd /home/devops/Assessment/nodejs-webapp && git pull
