name: Sync Code base
on:
  push:
    branches:
      - feature/Update-Codebase-Pipeline

jobs:
  update-code:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        git config --global user.email "jajitha.k@gmail.com"
        git config --global user.name "Jajitha"
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        host: ${{ secrets.VM_IP_ADDRESS }}
        port: 22
        user: ${{ secrets.VM_USERNAME }}
        pass: ${{ secrets.VM_PASSWORD }}
    - name: install ssh keys
      run: |
        mkdir -p ~/.ssh
        install -m 600 /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VM_IP_ADDRESS }} > ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP_ADDRESS }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit"
    - name: cleanup
      run: rm -rf ~/.ssh