name: Sync Code base
on:
  push:
    branches:
      - feature/Update-Codebase-Pipeline

jobs:
  update-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        host: ${{ secrets.VM_IP_ADDRESS }}
        port: 22
        user: ${{ secrets.VM_USERNAME }}
        pass: ${{ secrets.VM_PASSWORD }}
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa ${{ secrets.VM_IP_ADDRESS }} >> ~/.ssh/known_hosts

    - name: Access VM Folder
      run: |
        ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP_ADDRESS }}
        whoami