name: Sync Code base
on:
  push:
    branches:
      - master

jobs:
  update-code:
    runs-on: ubuntu-latest

    steps:
    - name: Update Code on VM
      uses: actions/checkout@v4
      with:
        host: 38.242.224.120
        username: devops
        password: ${{ secrets.VM_PASSWORD }}
        script: |
          cd /Assessment/nodejs-webapp
          git pull origin main
