name: Sync Codebase

on:
  merge:
    branches:
      - master

jobs:
  update-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Codebase
        run:  |
          git checkout master
          git pull
        #pulls latest code to the local folder
